export default {
  categories: 'Kategoriler',
  homeScreen: 'Anasayfa',
  basket: 'Sepetim',
  account: 'Hesabım',
  topDeals: 'Kampanyalı Ürünler',
  sort: 'Sırala',
  contackInfo: 'İletişim Bilgileri',
  firstName: 'Ad',
  surname: 'Soyad',
  phone: 'Telefon',
  emailAndPassword: 'E-posta & Şifre',
  email: 'E-Posta',
  password: 'Şifre',
  save: 'Kaydet',
};
