export default {
  categories: 'Kategoriler',
  homeScreen: 'Anasayfa',
  basket: 'Sepetim',
  account: 'Hesabım',
  topDeals: 'Kampanyalı Ürünler',
  sort: 'Sırala',
  contackInfo: 'İletişim Bilgileri',
  firstName: 'Ad',
  surname: 'Soyad',
  phone: 'Telefon',
  emailAndPassword: 'E-posta & Şifre',
  email: 'E-Posta',
  password: 'Şifre',
  save: 'Kaydet',
  order: 'Siparişlerim',
  favorites: 'Favorilerim',
  address: 'Adreslerim',
  userInfo: 'Kullanıcı Bilgileri',
  changePassword: 'Şifre Değiştir',
  logout: 'Çıkış yap',
};
